# -*- coding: UTF-8 -*-
from nltk.corpus import stopwords

stop_words_slovene = set(stopwords.words("slovenian")).union(set(
        [ "ali", "ampak","bodisi","in","kajti","ne", "niti", "oziroma", "pa","saj", "sicer","ter", "toda", "torej",
         "ter","nov","novo","kljub", "nasproti","navkljub", "navzlic" ,"proti" , "nova","zato","še", "zaradi", "a", "ali", "april", "avgust",
          "b", "bi", "bil", "bila", "bile", "bili", "bilo", "biti","blizu", "bo", "bodo", "bojo", "bolj", "bom", "bomo", "boste", "bova", "boš", "brez", "c", "cel", "cela",
         "celi", "celo", "d", "da", "daleč", "dan", "danes", "datum", "december", "deset", "deseta", "deseti", "deseto",
         "devet", "deveta", "deveti", "deveto", "do", "dober", "dobra", "dobri", "dobro", "dokler", "dol", "dolg",
         "dolga", "dolgi", "dovolj", "drug", "druga", "drugi", "drugo", "dva", "dve", "e", "eden", "en", "ena", "ene",
         "eni", "enkrat", "eno", "etc.", "f", "februar", "g", "g.", "ga", "ga.", "gor", "gospa", "gospod", "h", "halo",
         "i", "idr.", "ii", "iii", "in", "iv", "ix", "iz", "j", "januar", "jaz", "je", "ji", "jih", "jim", "jo",
         "julij", "junij", "jutri", "k", "kadarkoli", "kaj", "kajti", "kako", "kakor", "kamor", "kamorkoli", "kar",
         "karkoli", "katerikoli", "kdaj", "kdo", "kdorkoli", "ker", "ki", "kje", "kjer", "kjerkoli", "ko", "koder",
         "koderkoli", "koga", "komu", "kot", "kratek", "kratka", "kratke", "kratki", "l", "lahka", "lahke", "lahki",
         "dve ","dvema","dveh ","šest ","šestdeset ","šestindvajset","šestintrideset", "šestnajst ","šeststo ","štiri ","štirideset ",
         "štiriindvajset", "štirinajst", "štiristo", "deset", "devet","devetdeset", "devetintrideset", "devetnajst ","devetsto ",
         "dvainšestdeset", "dvaindvajset ","dvajset ","dvanajst ","dvesto ","enaindvajset", "enaintrideset", "enajst ","nič ",
         "osem ","osemdeset", "oseminštirideset", "osemindevetdeset ","osemnajst ","pet ","petdeset", "petinštirideset", "petindevetdeset ","petindvajset ",
         "petinosemdeset ","petinpetdeset ","petinsedemdeset ","petintrideset ","petnajst ","petsto ","sedem ","sedemdeset", "sedeminšestdeset",
         "sedemindvajset ","sedeminpetdeset ","sedemnajst ","sedemsto ","sto ","tisoč ","tri ","trideset ","triinšestdeset", "triindvajset ","triinpetdeset ",
         "trinajst ","tristo ","šestdesetim", "šestim ","šestindvajsetim ","šestintridesetim","šestnajstim","šeststotim ","štiridesetim",
         "lahko", "le", "lep", "lepa", "lepe", "lepi", "lepo", "leto", "m", "maj", "majhen", "majhna", "majhni",
         "malce", "malo", "manj", "marec", "me", "med", "medtem", "mene", "mesec", "mi", "midva", "midve", "mnogo","tretja",
         "moj", "moja", "moje", "mora", "morajo", "moram", "moramo", "morate", "moraš", "morem", "mu", "n", "na", "nad","naša",
         "naše", "ne", "nedavno", "nedelja", "nek","naj", "najina", "najino", "najmanj", "naju", "največ", "nam", "narobe", "nas", "nato", "nazaj", "naš",
         "neke","neka", "nekaj", "nekatere", "nekateri", "nekatero", "nekdo", "nekega", "neki", "nekje", "neko", "nekoga", "nekoč", "ni", "nikamor", "nikdar", "nikjer", "nikoli",
         "nič", "nje", "njega", "njegov", "njegova", "njegovo", "njej", "njemu", "njen", "njena", "njeno", "nji",
         "njih", "njihov", "njihova", "njihovo", "njiju", "njim", "njo", "njun", "njuna", "njuno", "no", "nocoj",
         "november","oba", "obe", "oboje", "od", "odprt", "odprta", "odprti", "okoli", "oktober",
         "on", "onadva", "one", "oni", "onidve", "osem", "osma", "osmi", "osmo", "oz.", "p", "pa", "pet", "peta",
         "petek", "peti", "peto", "po", "pod", "pogosto", "poleg", "poln", "polna", "polni", "polno", "ponavadi",
         "ponedeljek", "ponovno", "potem", "povsod", "pozdravljen", "pozdravljeni", "prav", "prava", "prave", "pravi",
         "pravo", "prazen", "prazna", "prazno", "prbl.", "precej", "pred", "prej", "preko", "pri", "pribl.",
         "približno", "primer", "pripravljen", "pripravljena","prva","npr.", "o", "ob", "prvi", "prvo", "pripravljeni", "proti","r",
         "ravno", "redko", "res", "reč", "s", "saj", "sam", "sama", "same", "sami", "samo", "se", "sebe", "sebi",
         "sedaj", "sedem", "sedma", "sedmi", "sedmo", "sem", "september", "seveda", "si", "sicer", "skoraj", "skozi",
         "slab", "smo", "srednji", "sta", "ste", "stran", "stvar", "sva","ta", "tak", "taka", "take", "taki", "tako", "takoj", "tam", "te", "tebe", "tebi", "tega", "težak",
         "težka", "težki", "težko", "ti", "tista", "tiste", "tisti", "tisto", "tj.", "tja", "to", "toda", "torek",
         "tri", "tu", "tudi", "tukaj", "tvoj", "tvoja", "tvoje", "u", "v", "vaju", "vam","ve", "vedno", "velik", "velika", "veliki",
         "vas", "vaš", "vaša", "vaše",  "veliko", "vendar", "ves", "več","š", "šest", "šesta", "šesti",
         "vi", "vidva", "vii", "viii", "visok", "visoka", "visoke", "visoki", "vsa", "vsaj", "vsak", "vsaka", "vsakdo",
         "vsake", "vsaki", "vsakomur", "vse", "vsega", "vsi", "vso", "včasih", "včeraj", "x", "z", "za", "zadaj",
         "zadnji", "zakaj", "zaprta", "zaprti", "zaprto", "zdaj", "zelo", "zunaj", "č", "če", "često", "četrta",
         "četrtek", "četrti", "četrto", "čez", "čigav","ž", "že","ampak", "lahek", "lahka", "lahko", "morati"
         "svoj", "jesti", "kak", "www", "km", "eur", "pač", "del", "kljub", "šele", "prek",
         "preko", "znova", "morda","kateri","katero","katera","imeti", "iti", "torej","dovolil", "hotel", "maral", "mogel",
         "moral", "smel", "zmogel", "želelo", "dovolilo", "hotelo ", "maralo ", "moglo ", "moralo ", "smelo ", "zmogl"]))

